zk:
    image: docker-kafka:2.10-0.8.2.0
    command: /bin/start_zk.sh
    #ports:
    #    - "2181:2181"
kafka:
    image: docker-kafka:2.10-0.8.2.0
    command: /bin/start_kafka.sh
    links:
        - zk
    #ports:
    #    - "9092:9092"
